= SNS REST API Guide
JUNWOO ;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

본 프로젝트는 사진형 SNS의 REST API를 구현하는 것을 목적으로 하고 있습니다.


[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===


[[resources]]
= 리소스


[[resources-token]]
== 토큰

토큰은 회원 로그인을 위해 사용된다.

[[resources-token-post]]
=== 토큰 발급

`POST` 요청을 사용하여 토큰을 발급 받을 수 있다.

operation::get-token[snippets='http-request,request-body,request-headers,request-parameters,curl-request,http-response,response-body,response-fields']

[[resources-token-get]]
=== 토큰 이용한 로그인

토큰을 이용한 로그인

operation::oauth-authorization[snippets='http-request,curl-request,http-response']


[[resources-account]]
== 회원

회원 리소스는 회원가입 혹은 회원정보 수정할 때, 회원탈퇴에 사용한다.

[[resources-accounts-post]]
=== 회원가입

`POST` 요청을 사용해서 새 회원을 만들 수 있다.

operation::create-account[snippets='request-headers,request-fields,curl-request,http-request,response-fields,http-response']


[[resources-accounts-update]]
=== 회원정보 수정

`PUT` 요청을 사용해서 기존 회원정보를 수정할 수 있다.

operation::update-account[snippets='http-request,request-headers,request-fields,curl-request,http-response,response-headers,response-fields']

[[resources-accounts-delete]]
=== 회원탈퇴

`DELETE` 요청을 사용해서 기존 회원이 탈퇴할 수 있다.

operation::delete-account[snippets='request-headers,request-fields,curl-request,http-response']

[[resources-post]]
== 게시글

게시글 리소스는 게시글을 만들거나 조회할 때 사용한다.

[[resources-post-list]]
=== 게시글 목록 조회

`GET` 요청을 사용하여 서비스의 모든 게시글을 조회할 수 있다.

operation::get-posts[snippets='request-headers, request-parameters, response-fields,curl-request,http-response']

[[resources-posts-post]]
=== 게시글 생성

`POST` 요청을 사용해서 새 게시글을 만들 수 있다.

operation::create-post[snippets='request-headers,request-fields,curl-request,response-body,response-fields,http-response']

[[resources-posts-get]]
=== 게시글 조회

`Get` 요청을 사용해서 기존 게시글 하나를 조회할 수 있다.

operation::get-posts[snippets='request-fields,curl-request,http-response']

[[resources-posts-update]]
=== 게시글 수정

`PUT` 요청을 사용해서 기존 게시글을 수정할 수 있다.

operation::update-post[snippets='request-headers,request-fields,curl-request,response-body,response-fields,http-response']

[[resources-posts-delete]]
=== 게시글 삭제

`DELETE` 요청을 사용해서 기존 게시글을 삭제할 수 있다.

operation::delete-post[snippets='request-fields,curl-request,http-response']


[[resources-comment]]
== 댓글

게시글 리소스는 댓글을 만들거나 조회할 때 사용한다.

[[resources-comment-list]]
=== 댓글 조회

`GET` 요청을 사용하여 게시글의 댓글을 조회할 수 있다.

operation::get-comments[snippets='request-headers, request-parameters, response-fields,curl-request,http-response']

[[resources-comments-post]]
=== 댓글 생성

`POST` 요청을 사용해서 새 댓글을 만들 수 있다.

operation::create-comment[snippets='request-headers,request-fields,curl-request,response-body,response-fields,http-response']


[[resources-comments -update]]
=== 댓글 수정

`PUT` 요청을 사용해서 기존 댓글을 수정할 수 있다.

operation::update-comment[snippets='request-headers,request-fields,curl-request,response-body,response-fields,http-response']

[[resources-posts-delete]]
=== 댓글 삭제

`DELETE` 요청을 사용해서 기존 댓글을 삭제할 수 있다.

operation::delete-comment[snippets='request-fields,curl-request,http-response']


[[resources-like]]
== 좋아요

[[resources-like-post]]
=== 좋아요 생성

'POST' 요청을 통해서 기존 포스트에 좋아요를 생성할 수 있다.

operation::create-like[snippets='request-headers, request-fields, http-response']

[[resources-like-delete]]
=== 좋아요 취소

'DELETE' 요청을 통해서 기존 포스트에 좋아요를 취소할 수 있다.

operation::cancel-like[snippets='request-headers, request-fields, http-response']



