language: java
jdk: oraclejdk8


before_install:
  - chmod +x mvnw
  -

sudo: required


script:
  # BUILD
  - ./mvnw clean package


before_deploy:
  - chmod 755 ./target/*.jar
  - zip -r spring-boot-practice *
  - mkdir -p deploy
  - mv spring-boot-practice.zip deploy/spring-boot-practice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: today-i-learn-deploy # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      repo: junwoochoi/spring-boot-practice
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: today-i-learn-deploy # S3 버킷
    key: spring-boot-practice.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: spring-boot-practice-sns    # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: spring-boot-practice-sns-group    # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: junwoochoi/spring-boot-practice
      branch: master

after_success:
  - mvn jacoco:report coveralls:report