spring:
  profiles:
    active: local

---


spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/postgres
   username: postgres
   password: test
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create-drop

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      apache:
        http: DEBUG

server:
  max-http-header-size: 160KB

my-app:
  client-id: myapp
  secret: secret
  test-email: test@email.com
  test-password: test