

spring:
  # IDENTITY
  application:
    name: @project.artifactId@
  profiles:
    active: local # 기본 환경 선택


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
    max-http-header-size: 160KB

my-app:
  client-id: myapp
  secret: secret
  test-email: test@email.com
  test-password: test

# local 환경
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        use-sql-comments: true
        ddl-auto: create-drop
        temp:
          use_jdbc_metadata_defaults: false




# 운영 환경
---

spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081

---

spring.profiles: set2
spring.profiles.include: real-db


server:
  port: 8082

---
