

spring:
  # IDENTITY
  application:
    name: @project.artifactId@
  profiles:
    active: local


  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
    max-http-header-size: 160KB

# S3 설정
cloud:
  aws:
    s3:
      bucket: 'today-i-learn-deploy'
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true

# test용 my-app
my-app:
  client-id: myapp
  secret: secret
  test-email: test@email.com
  test-password: test

# local
---
spring:

  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: junsta
    password: junsta
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
        use-sql-comments: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
---

spring.profiles: set1
spring.profiles.include: real-db

server:
  port: 8081

---

spring.profiles: set2
spring.profiles.include: real-db


server:
  port: 8082

---
